apiVersion: v2
name: acdh-imgproxy
description: ACDH imgproxy deployment with an Nginx transformation cache
type: application
version: 0.2.2
appVersion: "4"
home: https://github.com/acdh-oeaw/imgproxy-helm
icon: https://cdn.rawgit.com/imgproxy/imgproxy/master/logo.svg
sources:
  - https://github.com/acdh-oeaw/imgproxy-helm
  - https://github.com/imgproxy/imgproxy-helm
maintainers:
  - name: ACDH-CH
    url: https://www.oeaw.ac.at/acdh
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - kind: added
      description: Initial release with the upstream imgproxy chart and an Nginx transformation cache
dependencies:
  - name: imgproxy
    version: 1.1.0
    repository: https://helm.imgproxy.net/
